### ISSUE TITLE
[Feat] Events 페이지 구성 (배너 컴포넌트 추가)

### ISSUE THREAD

**Issue by 1017yu** [FastSubTeam/front#10]
## 💡 기능 설명
등록된 이벤트들을 모두 담는 events 컴포넌트 구성

## 📝 ToDo
- [ ] events 컴포넌트 생성
- [ ] Router에 내에 events 라우터 구성
- [ ] Banner 컴포넌트 생성
