### ISSUE TITLE
[Feat] 회원 커뮤니티 게시글 상세 보기 페이지

### ISSUE THREAD

**Issue by oceanlee-seoul** [FastSubTeam/front#40]
## 💡 기능 설명
회원 커뮤니티 게시글 상세 보기 페이지

<img width="883" alt="스크린샷 2023-07-26 오후 5 10 33" src="https://github.com/FastSubTeam/front/assets/108586797/a11ffcab-6108-4d85-a70d-667ec1409df4">

## 📝 ToDo

- [x] 게시글 상세 보기 페이지 레이아웃, UI 작업
- [x] 반응형
- [ ] postId로 데이터 가져오는 API 연결
- [ ] 로그인 정보 확인하여 게시글 수정 버튼 연결

- 댓글 기능

- [x] 댓글 작성 및 댓글 조회 레이아웃, UI 작업
- [ ] 댓글 작성 API 연결
- [ ] 로그인 정보 확인하여 댓글 수정 버튼 연결
- [ ] 댓글 수정 UI
