### ISSUE TITLE
[Feat] 종료된 수요조사 결과 목록 조회 

### ISSUE THREAD

**Issue by EungBug** [FastSubTeam/front#60]
## 💡 기능 설명

종료된 수요조사 결과 목록 조회 

## 📝 ToDo

- [x] 수요조사 목록 테이블
- [x] 수요조사 목록 조회 api 연동
- [x] 수요조사 아이템 선택 시 결과 상세 화면으로 이동
